num = input('Digite um numero de 0 a 9999: ')
print('Ex: Digite um número:1834\n')
print('Seu numero digitado foi {}, e ele tem;'.format(num))
print('unidade:{}'.format(num[3]))
print('dezena:{}'.format(num[2]))
print('centena:{}'.format(num[1]))
print('milhar:{}'.format(num[0]))